from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle,
    Image,
)
import os


def generate_pdf(reference_text,
                 transcription,
                 similarity,
                 score,
                 grade,
                 audio_features,
                 waveform_path):

    base_dir = os.path.dirname(os.path.abspath(__file__))
    report_dir = os.path.join(base_dir, "reports")
    os.makedirs(report_dir, exist_ok=True)

    pdf_path = os.path.join(report_dir, "Communication_Report.pdf")

    doc = SimpleDocTemplate(pdf_path)

    styles = getSampleStyleSheet()

    story = []

    # ---------------- Title ----------------

    title = Paragraph(
        "<font size=20><b>Voice-Based Communication Understanding Analyzer</b></font>",
        styles["Title"],
    )

    story.append(title)
    story.append(Spacer(1, 20))

    # ---------------- Reference ----------------

    story.append(Paragraph("<b>Reference Concept</b>", styles["Heading2"]))
    story.append(Paragraph(reference_text, styles["BodyText"]))
    story.append(Spacer(1, 15))

    # ---------------- Transcription ----------------

    story.append(Paragraph("<b>Student Transcription</b>", styles["Heading2"]))
    story.append(Paragraph(transcription, styles["BodyText"]))
    story.append(Spacer(1, 15))

    # ---------------- Waveform ----------------

    if os.path.exists(waveform_path):
        story.append(Paragraph("<b>Audio Waveform</b>", styles["Heading2"]))
        story.append(Image(waveform_path, width=450, height=180))
        story.append(Spacer(1, 15))

    # ---------------- Evaluation Table ----------------

    data = [
        ["Metric", "Value"],
        ["Semantic Similarity", f"{similarity:.2f}"],
        ["Understanding Score", f"{score}/100"],
        ["Classification", grade],
        ["Duration", f"{audio_features['Duration']:.2f} sec"],
        ["RMS Energy", f"{audio_features['RMS Energy']:.4f}"],
    ]

    table = Table(data, colWidths=[220, 220])

    table.setStyle(
        TableStyle([
            ("BACKGROUND", (0,0), (-1,0), colors.darkblue),
            ("TEXTCOLOR", (0,0), (-1,0), colors.white),
            ("GRID", (0,0), (-1,-1), 1, colors.black),
            ("BACKGROUND", (0,1), (-1,-1), colors.beige),
            ("FONTNAME", (0,0), (-1,0), "Helvetica-Bold"),
            ("ALIGN", (0,0), (-1,-1), "CENTER"),
            ("BOTTOMPADDING", (0,0), (-1,0), 10),
        ])
    )

    story.append(Paragraph("<b>Evaluation Summary</b>", styles["Heading2"]))
    story.append(table)
    story.append(Spacer(1, 20))

    # ---------------- Feedback ----------------

    if similarity >= 0.80:
        feedback = (
            "Excellent understanding of the concept. The explanation closely "
            "matches the reference."
        )
    elif similarity >= 0.60:
        feedback = (
            "Moderate understanding. Include more important keywords and improve "
            "clarity."
        )
    else:
        feedback = (
            "Poor understanding. The explanation differs significantly from the "
            "reference concept."
        )

    story.append(Paragraph("<b>Feedback</b>", styles["Heading2"]))
    story.append(Paragraph(feedback, styles["BodyText"]))

    story.append(Spacer(1, 30))

    story.append(
        Paragraph(
            "<font size=10><i>Generated by Voice-Based Communication Understanding Analyzer</i></font>",
            styles["Normal"],
        )
    )

    doc.build(story)

    return pdf_path
